resources:
  - name: docker-cache-run.dbp_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.var.gitProvider }}
      path: {{ .Values.var.path }}
      branches:
        include: {{ .Values.var.branches }} 

  - name: docker-cache-run.dbp_image
    type: Image
    configuration:
      registry: {{ .Values.var.artifactory }}
      sourceRepository: {{ .Values.var.repo }}               # <-- required if registry is Artifactory
      imageName: {{ .Values.var.imageName }}
      imageTag: latest
      autoPull: true
      

pipelines:
  - name: {{ .Values.var.pipelineName }}
    configuration:
      nodePool: {{ .Values.var.nodePool }}
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: docker_build_push
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: {{ .Values.var.imageName }}   # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: docker-cache-run.dbp_repo
          integrations:
            - name: {{ .Values.var.artifactory }}                             # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: docker_build_push
          autoPublishBuildInfo: false
          forceXrayScan: false
          targetRepository: {{ .Values.var.repo }}
          integrations:
            - name: {{ .Values.var.artifactory }}                             # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: docker-cache-run.dbp_image